# Generated by Django 3.2.7 on 2021-11-12 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_user_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(default='consultor', max_length=15, verbose_name='Rol'),
        ),
    ]
