# Generated by Django 3.2.7 on 2021-11-12 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.CharField(default='consultor', max_length=12, verbose_name='Rol'),
        ),
    ]
