# Generated by Django 3.2.7 on 2021-11-15 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0003_alter_user_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=150, null=True, verbose_name='Email'),
        ),
    ]
